# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumable_per_day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.AnimalGroup')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumableGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumableType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.ConsumableGroup')),
            ],
        ),
        migrations.CreateModel(
            name='SuppliedAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_count', models.IntegerField()),
                ('animal_gender', models.CharField(choices=[(0, 'male'), (1, 'female')], max_length=255)),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.AnimalType')),
            ],
        ),
        migrations.CreateModel(
            name='SuppliedConsumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumable_count', models.IntegerField()),
                ('consumable_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.ConsumableType')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='suppliedconsumable',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Supply'),
        ),
        migrations.AddField(
            model_name='suppliedanimal',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.Supply'),
        ),
        migrations.AddField(
            model_name='animalneed',
            name='animal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.AnimalType'),
        ),
        migrations.AddField(
            model_name='animalneed',
            name='consumable_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.ConsumableType'),
        ),
    ]
